### ISSUE TITLE
[Task] Update to Quarkus 2.7

### ISSUE THREAD

**Issue by ebaron** [cryostatio/jfr-datasource#108]
This project is currently using Quarkus 1.11. We should update to a newer version, ideally 2.7. The process for migrating versions is documented on the Quarkus wiki. We should begin with the migration guide for 1.12, and then proceed one minor version at a time:
- [1.12](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-1.12)
- [1.13](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-1.13)
- [2.0](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.0)
- [2.1](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.1)
- [2.2](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.2)
- [2.3](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.3)
- [2.4](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.4)
- [2.5](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.5)
- [2.6](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.6)
- [2.7](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.7)

**Comment by tthvo** [comment]
**Migration Guide 1.3**

> All application.properties files found in the classpath are loaded in the Quarkus configuration. Files in the current application will have priority and files in dependencies will use the classloader order. This means, that your Quarkus application may pick up additional configuration that was not picked up previously and possible change the behaviour of your application.

@ebaron Hi Elliott, I wonder how to best check if any of our dependencies might have an `application.properties` file that might cause this issue? Or is this issue not applicable to our case?

**Comment by ebaron** [comment]
> Hi @ebaron Thanks a lot! That was smooth and it came up empty for me too (I think it was moved to `target/quarkus-app/lib/boot` and `target/quarkus-app/lib/main` for `Quarkus v1.12 ` up).
> 
> Also, starting `v1.12`, Fast-jar is the default and they are placed under `target/quarkus-app`. Is that something similar to this work-around in our `pom.xml`? If it is, is it safe to remove these? For me, there is currently no `jfr-datasource-2.2.0-SNAPSHOT-runner.jar` output if I used Quarkus 1.12.
> 
> ```
> 
>       <plugin>
>         <groupId>org.codehaus.mojo</groupId>
>         <artifactId>build-helper-maven-plugin</artifactId>
>         <version>${build-helper-maven-plugin.version}</version>
>         <executions>
>           <execution>
>             <id>attach-artifacts</id>
>             <phase>package</phase>
>             <goals>
>               <goal>attach-artifact</goal>
>             </goals>
>             <configuration>
>               <artifacts>
>                 <artifact>
>                   <file>${project.build.directory}/${project.build.finalName}-runner.jar</file>
>                   <classifier>runner</classifier>
>                   <type>jar</type>
>                 </artifact>
>               </artifacts>
>             </configuration>
>           </execution>
>         </executions>
>       </plugin>
> ```

I think it's safe to remove this. I didn't need it when building the Cryostat Reports project with a newer version of Quarkus, and we can always revisit it if needed once the upgrade is done. Please also remove the `build-helper-maven-plugin.version` property which will be unused now, I believe.

**Comment by tthvo** [comment]
@ebaron Is it a better way to use RESTEasy Reactive like in Cryostat Reports than the current reactive route?

Here I read in the blog but I am not quite sure which one is a better fit for us?

> Reactive Routes were initially introduced to provide a reactive execution model for HTTP APIs on top of the [Quarkus Reactive Architecture](https://quarkus.io/guides/quarkus-reactive-architecture). With the introduction of [RESTEasy Reactive](https://quarkus.io/guides/resteasy-reactive), you can now implement reactive HTTP APIs and still use JAX-RS annotations. Reactive Routes are still supported, especially if you want a more route-based approach, and something closer to the underlying reactive engine.
