### ISSUE TITLE
Injected beans not supported in NativeImageTest

### ISSUE THREAD

**Issue by tthvo** [cryostatio/jfr-datasource#110]
It seems adding mock in ` QuarkusTest` breaks the `NativeImageTest` as it said injected field returns null.

```
[ERROR] Errors: 
[ERROR]   NativeDatasourceIT>DatasouceTest.testDeleteAllFiles:634 » NullPointer
[ERROR]   NativeDatasourceIT>DatasouceTest.testDeleteAllIOFail:735 » NullPointer
[ERROR]   NativeDatasourceIT>DatasouceTest.testDeleteFileExist:443 » NullPointer
[ERROR]   NativeDatasourceIT>DatasouceTest.testDeleteFileIOFail:563 » NullPointer
[ERROR]   NativeDatasourceIT>DatasouceTest.testDeleteFileNotExist:518 » NullPointer
[ERROR]   NativeDatasourceIT>DatasouceTest.testGetList:174 » NullPointer
[ERROR]   NativeDatasourceIT>DatasouceTest.testGetListEmpty:260 » NullPointer
[ERROR]   NativeDatasourceIT>DatasouceTest.testGetSearch:316 » NullPointer
[ERROR]   NativeDatasourceIT>DatasouceTest.testPostLoad:133 » NullPointer
[ERROR]   NativeDatasourceIT>DatasouceTest.testPostQueryTable:399 » NullPointer
[ERROR]   NativeDatasourceIT>DatasouceTest.testPostQueryTimeseries:355 » NullPointer
[ERROR]   NativeDatasourceIT>DatasouceTest.testPostSet:92 » NullPointer
[ERROR]   NativeDatasourceIT>DatasouceTest.testPostUpload:54 » NullPointer
```

I read the [documentation](https://javadoc.io/static/io.quarkus/quarkus-junit5/1.13.3.Final/io/quarkus/test/junit/NativeImageTest.html). Here is what they say.

> This also means that injection of beans into a test class using @Inject is not supported in native image tests. Such injection is only possible in tests injected with @QuarkusTest so the test class structure must take this into account.

Is there a way to work around it or should we have a separate test class `NativeDatasourceIT` for native image instead of extending the  base `DatasouceTest`?

**Comment by tthvo** [comment]
@andrewazores any suggestions?

**Comment by andrewazores** [comment]
That's unfortunate. I think having a separate `NativeDatasourceIT` that does not extend the base `DatasourceTest` sounds good. The native-specific test can't have the mock(s) injected and so the tests can't cover all of the behaviour in the same way, so it will be missing the IOException/HTTP 500 tests for example, but it would be good to at least have tests to verify that it does behave as expected in the "happy path" scenarios.
