### ISSUE TITLE
Incorrect `Content-Type` response headers

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/jfr-datasource#123]
ex.

```bash
$ http :8080/list
HTTP/1.1 200 OK
Access-Control-Allow-Headers: accept, content-type
Access-Control-Allow-Methods: POST
Access-Control-Allow-Origin: *
content-length: 108
content-type: application/json

es-andrewazor-demo-Main_auto_foo_20220802T155132Z.jfr
es-andrewazor-demo-Main_auto_foo_20220802T155202Z.jfr
```

The `content-type` response header is `application/json`, but the response body itself clearly is not JSON-formatted.

**Comment by tthvo** [comment]
@andrewazores Would we start setting the response body in JSON-format in all routes? Or right now text/plain is good enough?

**Comment by andrewazores** [comment]
I think for now I'd prefer to just correct the header to `text/plain`. It makes sense to use `application/json` but until we have more use cases and a better idea of what we want to do with each endpoint we should just leave the response body formats as-is.
