### ISSUE TITLE
Incorrect displayed value of jdk.CompilerStatistics.peakTimeSpent event

### ISSUE THREAD

**Issue by tthvo** [cryostatio/jfr-datasource#127]
Looking into grafana, we see the displayed value is `409`:

![Screenshot from 2022-09-21 17-58-17](https://user-images.githubusercontent.com/68053619/191617951-e1dab9f0-1b2a-4175-88ec-d4dbe87d6808.png)

However, in summary of the jfr, it was `361.000ms` instead:
```bash
jdk.CompilerStatistics {
  startTime = 21:14:30.517
  compileCount = 3764
  bailoutCount = 13
  invalidatedCount = 0
  osrCompileCount = 23
  standardCompileCount = 3741
  osrBytesCompiled = 0 bytes
  standardBytesCompiled = 0 bytes
  nmethodsSize = 6.3 MB
  nmethodCodeSize = 4.3 MB
  peakTimeSpent = 361.000 ms
  totalTimeSpent = 3.809 s
}
```

Source: [summary.txt](https://github.com/cryostatio/jfr-datasource/files/9619961/summary.txt)

**Comment by tthvo** [comment]
Query target's specified as:
```bash
targets: [
  {
    target:"jdk.CompilerStatistics.peakTimeSpent",
    refId:"A",
    hide:undefined,
    type:"timeserie"
  }
]
```

And all datapoints return `409` but would it need to be `361`? Or is there a specfic calculation for this field?

Any guide @andrewazores ?

**Comment by tthvo** [comment]
I think some other panel displays the incorrect units (might need a common conversion on jfr?) and x-y values inverted (i.e memory used shown inverted for me).

**Comment by andrewazores** [comment]
I'm not sure exactly how that number is getting pulled out of the JFR file. Presumably there are multiple of the `jdk.CompilerStatistics` events in the recording? Or is there only that one that you pasted?

**Comment by tthvo** [comment]
Oh yes there are multiple events of this type. But the `jdk.CompilerStatistics.peakTimeSpent` shows the same `361.000 ms`

**Comment by andrewazores** [comment]
https://github.com/cryostatio/cryostat-grafana-dashboard/issues/11#issuecomment-1255316712

In this example my `peakTimeSpent` and the chart agree with each other...

**Comment by tthvo** [comment]
Hmm interesting! I will check with multiple recordings and datasource impl to see what happened then.

**Comment by tthvo** [comment]
Okayy, the description in the summary file was from another recording that I didn't notice. Sorry for not noticing that :D

I will close this issue as it is not a bug.
