### ISSUE TITLE
[Task] Replace deprecated getAttributes method

### ISSUE THREAD

**Issue by tthvo** [cryostatio/jfr-datasource#182]
> Looks good to me! Just a question:

> https://github.com/cryostatio/jfr-datasource/blob/6ef4b9bb97751b36f6fbd8a27f691e0c4b6fc0fc/src/main/java/io/cryostat/jfr/datasource/events/RecordingService.java#L144

> I am receiving deprecated warning here. Is there a new way to do this?

_Originally posted by @tthvo in https://github.com/cryostatio/jfr-datasource/pull/160#pullrequestreview-1386244727_

**Comment by mwangggg** [comment]
`getAttributes()` and `ITemToolkit.accessor(attribute)` are both functions that have had the deprecation warning for over 5 years now. Seems like they haven't gotten round to removing them and there's no info about any replacements ...
