### ISSUE TITLE
[Task] Provide instructions for podman

### ISSUE THREAD

**Issue by jiekang** [cryostatio/jfr-datasource#23]
Provide instructions that use podman and it's related tools instead of the existing docker-based instructions

**Comment by jiekang** [comment]
Possible blocker: may need configuration for s2i to use the podman image registry

**Comment by andrewazores** [comment]
Closing as this appears to be outdated. The README uses Podman and quay.io now, nothing Docker-related other than the name of `Dockerfile` that is used by Podman.
