### ISSUE TITLE
[Task] Show currently selected file

### ISSUE THREAD

**Issue by jiekang** [cryostatio/jfr-datasource#34]
Users can select which file to use. There should be API to show the currently selected file. One way would be to augment `/list` to also highlight the selected file in some manner, for example surrounded by asterisks.

**Comment by andrewazores** [comment]
Related #90

**Comment by maxcao13** [comment]
@andrewazores is this still a feature that needs to be done?

**Comment by andrewazores** [comment]
Sure, it's fairly low-priority because we have no direct and immediate use case for it within Cryostat, but it's a good enhancement to jfr-datasource in its own right. It will come in handy for Cryostat some time in the future when we start paying more attention to the Grafana integration.
