### ISSUE TITLE
[Task] Allow default dashboard to be loaded from the server

### ISSUE THREAD

**Issue by jiekang** [cryostatio/jfr-datasource#38]
Users can import the default dashboard json file from their computer. The server can host the file so they can import it from the server instead.

**Comment by andrewazores** [comment]
Closing as no longer relevant - the JSON referenced defines a Grafana dashboard, which is now baked in to the Cryostat Grafana Dashboard container image: https://github.com/cryostatio/cryostat-grafana-dashboard/blob/e3738c4d76366afc9a13479560cc6f1e6b673702/dashboard.json
