### ISSUE TITLE
[Task] API endpoint for deleting old JFR files

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/jfr-datasource#90]
There is currently no way to delete old files from the datasource. This means that over time, storage is simply eaten and can never be reclaimed except by removing the files by some external process. It should be possible to delete files individually, and it would also currently be useful for Cryostat's purposes to be able to delete all previously uploaded JFR files. This is because of the way that Cryostat currently interacts with the jfr-datasource, where Cryostat does not keep track of which files may have been previously uploaded to the datasource, nor does it query for which files the datasource already knows about when either Cryostat or the datasource are restarted, and neither Cryostat nor the datasource implement any way to confirm that a common filename really represents the same file contents (by a file hash for example). Cryostat simply treats jfr-datasource as a conversion service, sending a JFR file to the datasource as needed and, when a successful response is received, opening the Grafana dashboard so the user can view the resulting translated JFR->JSON timeseries data. If a "DELETE all" existed then Cryostat could always issue "DELETE all ; POST /load ; open Dashboard" sequence to implement its "View in Grafana" feature workflow without leaking storage resources over time.

**Comment by tthvo** [comment]
@andrewazores we would want a route to `DELETE all` or `DELETE file`? Or both?

**Comment by andrewazores** [comment]
We definitely want `DELETE {file}`, and `DELETE (all)` should be useful too.

**Comment by tthvo** [comment]
@andrewazores  Look like mentioned issue is not automatically close by PRs?
